# Site settings
title: Javier Sales-Ortiz
email: salesort@ualberta.ca
url: https://j27avier.github.io/
description: "Welcome to Javier's personal website! Javier is a graduate student from the University of Alberta, with experience in the fields of Machine Learning, Data Science and Robotics. This website serves as a showcase of Javier's work, providing his hilighted projects."
keywords: "computer science, mechatronics, cyberphysical systems, python, machine learning, optimization"
skills: "Machine Learning, Optimization, Data Science, Cyberphysical Systems"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 0f7070 #18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: 
  location: Location
  social: Around the Web
  credits: Contact

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: <i class="fa-brands fa-linkedin"></i>
    url: https://www.linkedin.com/in/javier-sales-ortiz/
  - title: <i class="fa-brands fa-github"></i>
    url: https://github.com/J27avier
    #  - title: stack-overflow
    # url: http://stackoverflow.com/questions/tagged/jekyll
  - title: <i class="fa-solid fa-graduation-cap"></i>
    url: https://scholar.google.com/citations?user=5bSpQkYAAAAJ&hl=en

# Postal address (add as many lines as necessary)
address:
  - line: Based in Edmonton,
  - line: Alberta, Canada

# Credits content
credits: 'salesort[at]ualberta[dot]com'

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
